### ISSUE TITLE
domain grid

### ISSUE THREAD

**Issue by migueldvb** [piernik-dev/piernik#121]
I am trying to understand how the grid is initialized. For example in the kepler problem the left and right domain boundaries are (-1,1) in the problem.par file but they are actually (-1.27606e+38,1.27606e+38) in the output files. Is there something wrong in the setup of this problem or how are the dimensions converted to cgs units?

**Comment by Xarthisius** [comment]
Piernik uses scaled units by default. Since length, time and mass units are arbitrary we have chosen "ridiculous" values (1 / tiny(float) in this case) as defaults. It's easier to catch errors this way. If you want meaningful units, you need to set them properly in *problem.par* (see *problems/sedov/problem.par.build-outflow*)

**Comment by migueldvb** [comment]
very nice! thank you for the pointer.
